[package]
name = "rocket_test"
version = "0.1.0"
authors = ["L_Sveinung <sveinuov@stud.ntnu.no>"]
publish = false

[dependencies]
rocket = "0.3.8"
rocket_codegen = "0.3.8"
rocket-auth-login = "*"
serde_json = "1.0.2"
serde = "1.0.11"
serde_derive = "1.0.11"
htmlescape = "0.3.1"