[package]
name = "conrod_test"
version = "0.1.0"
authors = ["Sveinung Øverland <sveinungg.overlandd@gmail.com>"]

[dependencies]
conrod = { version = "0.52.0", features = ["piston", "glium", "winit"] }
